version: '3.1'

services:

  db-test:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: formations-test
      POSTGRES_PASSWORD: formations-test
      POSTGRES_DB: formations-test
